### ISSUE TITLE
Are you open for some maintenance ?

### ISSUE THREAD

**Issue by williamdes** [Samyoul/U2F-php-server#8]
Hi @Samyoul 

I am one of the members of the phpMyAdmin team and phpMyAdmin packaging team for Debian.

[We use you package at phpMyAdmin](https://github.com/phpmyadmin/phpmyadmin/blob/84a9991a123a2be2941459eaa4b56171e437b2ad/composer.json#L81), and you can see it is recommended on the Debian page: https://packages.debian.org/fr/buster-backports/phpmyadmin

But, no Debian package exists for your repository. As I intend to package it into Debian I would need to be sure this repository is still alive.

I would need to make a pull-request to add unit tests if possible to provide [autopkgtests](https://ci.debian.net/packages/t/twig-i18n-extension/) in Debian and maybe some improvements.

Packaged example: https://salsa.debian.org/phpmyadmin-team/twig-i18n-extension

Please let me know if you are open for some maintenance or not.

**Comment by williamdes** [comment]
cc @Samyoul

**Comment by Samyoul** [comment]
Hey, thanks for reaching out. Sorry for the late reply I'd been taking some time with my family last week, just sifting through my backlog of emails.

So basically yes I am interested in maintenance.

Also I'm super flattered that phpMyAdmin uses my package.

I've also got working code for Fido 2 / web authn to upgrade this repo with.

**Comment by williamdes** [comment]
Hi !

No worries for the delay.

> So basically yes I am interested in maintenance.

Very cool !

> Also I'm super flattered that phpMyAdmin uses my package.

And I am very glad to know we use a package that has an active author :) 

> I've also got working code for Fido 2 / web authn to upgrade this repo with.

Awesome !


I submitted a bug to Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973258 and will start the packaging on https://salsa.debian.org/php-team/pear/php-u2f-php-server


So as you can see on https://salsa.debian.org/php-team/pear/php-u2f-php-server/-/pipelines the CI is [very sad](https://salsa.debian.org/php-team/pear/php-u2f-php-server/-/jobs/1113112#L1439) to have no way to auto test the package, I will try to write some tests.

Could you please try to help me to write a full package description below the small one line description ?
Here: https://salsa.debian.org/php-team/pear/php-u2f-php-server/-/blob/main/debian/control#L21

Example: https://salsa.debian.org/php-team/pear/php-dasprid-enum/-/blob/main/debian/control#L21
Render: https://packages.debian.org/unstable/php-dasprid-enum

**Comment by williamdes** [comment]
Hi @Samyoul 
I everything okay ?
I did not get any news from you in some time and no feedback on my PR #9 

Let me know :)

**Comment by williamdes** [comment]
🏓 ?

**Comment by williamdes** [comment]
Hi @Samyoul
I did not hear from you, is everything okay?

**Comment by williamdes** [comment]
Just sent you a last email about this
